### ISSUE TITLE
pystats never runs

### ISSUE THREAD

**Issue by colesbury** [facebookexperimental/free-threading-benchmarking#8]
If you check the "Also collect pystats for this commit" checkbox, then the job won't finish because the "collect-stats" step doesn't have a machine to run on.

See: https://github.com/facebookexperimental/free-threading-benchmarking/actions/runs/11372918029

Should it be running on the same machine as the benchmarking?

cc @mpage @yuqiw4

**Comment by yuqiw4** [comment]
I've noticed this issue weeks ago but didn't start working on it. It should be straight forward to fix. @mpage Please let me know if we need this and whether we should run it on the same machine.

**Comment by mpage** [comment]
@yuqiw4 - Yep, this is needed. I think it's fine to run on the same machine. Correct me if I'm wrong, but the runners will only execute one job at a time, so we don't need to worry about stats collection interfering with benchmarks that are running simultaneously on the same machine. The only downside to allowing them to run on the same machine is that it ties up a machine that could otherwise be running benchmarks. This seems fine given that we're not currently bottlenecked on benchmark runner capacity.

**Comment by mpage** [comment]
This should work now. Here are some example [pystats results](https://github.com/facebookexperimental/free-threading-benchmarking/blob/main/results/bm-20241018-3.14.0a1%2B-6d93690/bm-20241018-vultr-x86_64-python-main-3.14.0a1%2B-6d93690-pystats.md) from main.
